version: '3.8'
services:
  frontend:
    container_name: frontend
    # image: frontend
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    networks:
      - nestjs-network
  backend:
      container_name: backend
      # image: backend
      build:
          context: ./backend
          target: production
      ports:
          - 3000:3000
      networks:
          - nestjs-network
      working_dir: /app
      volumes:
          - ./:/app
          - /app/node_modules
      
      # command: npm run start:prod
      restart: unless-stopped  

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nestjs-network
networks:
  nestjs-network:
    driver: bridge
volumes:
    mongodb_data:
      driver: local
# This is a production version of the docker-compose file.